services:
  backend:
    build: .
    container_name: mms-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=your_jwt_secret_here
      - MONGO_URI=mongodb://root:example@mongodb:27017/mmsdb?authSource=admin
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    networks:
      - mms-net

  mongodb:
    build:
      context: ./mongo-db
    container_name: mms-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mmsdb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - mms-net

networks:
  mms-net:
    name: mms-net

volumes:
  mongo_data:
    name: mms-mongo-data